sonar.projectKey=BastienLeleu_CUBE3-backfront
sonar.organization=bastienleleu
sonar.projectName=CUBE3-front
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.host.url=https://sonarcloud.io
sonar.exclusions=**/node_modules/**, dist/**, **/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/**/lcov.info